//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbcvEntities : DbContext
    {
        public dbcvEntities()
            : base("name=dbcvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbladmin> tbladmin { get; set; }
        public virtual DbSet<tbldeneyimlerim> tbldeneyimlerim { get; set; }
        public virtual DbSet<tblegitimlerim> tblegitimlerim { get; set; }
        public virtual DbSet<tblhakkimda> tblhakkimda { get; set; }
        public virtual DbSet<tblhobilerim> tblhobilerim { get; set; }
        public virtual DbSet<tbliletisim> tbliletisim { get; set; }
        public virtual DbSet<tblsertifikalarim> tblsertifikalarim { get; set; }
        public virtual DbSet<tblyeteneklerim> tblyeteneklerim { get; set; }
        public virtual DbSet<tblsosyalmedyahesap> tblsosyalmedyahesap { get; set; }
        public virtual DbSet<tblsosyalmedya> tblsosyalmedya { get; set; }
    }
}
